channels:
  - conda-forge
  - defaults
dependencies:
  - av
  - numpy
  - packaging
  - pandas
  - pip
  - pyqt
  - pyyaml
  - quantities
  - tqdm
  - pip:
    - neo>=0.7.2
    - elephant>=0.6.2
    - ephyviewer>=1.1.0
    - pylttb
